/**
 * File generated by Magnet rest2mobile 1.1 - 23 Jan, 2018 6:31:39 PM
 * @see {@link http://developer.magnet.com}
 */

package com.visualphysics.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.visualphysics.controller.api.TestModel;
import com.visualphysics.controller.api.TestModelFactory;
import com.visualphysics.model.beans.*;

/**
* This is generated stub to test {@link TestModel}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class TestModelTest extends InstrumentationTestCase {
  private TestModel testModel;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    TestModelFactory controllerFactory = new TestModelFactory(magnetClient);
    testModel = controllerFactory.obtainInstance();

    assertNotNull(testModel);
  }

  /**
    * Generated unit test for {@link TestModel#listOfRecordsByTableName}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testListOfRecordsByTableName() throws SchemaException, ExecutionException, InterruptedException {
    Call<ListOfRecordsByTableNameResult> callObject = testModel.listOfRecordsByTableName(null);
    assertNotNull(callObject);

    ListOfRecordsByTableNameResult result = callObject.get();
    assertNotNull(result);
    //TODO : add more asserts
  }

}
