/**
 * File generated by Magnet rest2mobile 1.1 - 23 Jan, 2018 6:31:39 PM
 * @see {@link http://developer.magnet.com}
 */

package com.visualphysics.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.visualphysics.model.beans.*;

public interface TestModel {

  /**
   * Generated from URL POST http://www.meva.izisstechnology.in/api/MEVAAPI
   * POST api/MEVAAPI
   * @param listener
   * @return ListOfRecordsByTableNameResult
   */
  Call<ListOfRecordsByTableNameResult> listOfRecordsByTableName(StateChangedListener listener);
}
