/**
 * File generated by Magnet rest2mobile 1.1 - 23 Jan, 2018 6:31:39 PM
 * @see {@link http://developer.magnet.com}
 */

package com.visualphysics.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.visualphysics.model.beans.*;

public class TestModelFactory extends ControllerFactory<TestModel> {
  public TestModelFactory(MagnetMobileClient magnetClient) {
    super(TestModel.class, TestModelSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller TestModel
  public static class TestModelSchemaFactory extends AbstractControllerSchemaFactory {
    private static TestModelSchemaFactory __instance;

    public static synchronized TestModelSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new TestModelSchemaFactory();
      }

      return __instance;
    }

    private TestModelSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method listOfRecordsByTableName
      JMethod method1 = addMethod("listOfRecordsByTableName",
        "api/MEVAAPI",
        "POST",
        ListOfRecordsByTableNameResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://www.meva.izisstechnology.in");
    }

  }

}
