/**
 * File generated by Magnet rest2mobile 1.1 - 23 Jan, 2018 6:31:39 PM
 * @see {@link http://developer.magnet.com}
 */

package com.visualphysics.model.beans;


/**
 * Generated from json example
{
  "Response" : "Test"
}

 */

public class ListOfRecordsByTableNameResult {

  
@com.google.gson.annotations.SerializedName("Response")
  private String response;

  public String getResponse() {
    return response;
  }

  /**
  * Builder for ListOfRecordsByTableNameResult
  **/
  public static class ListOfRecordsByTableNameResultBuilder {
    private ListOfRecordsByTableNameResult toBuild = new ListOfRecordsByTableNameResult();

    public ListOfRecordsByTableNameResultBuilder() {
    }

    public ListOfRecordsByTableNameResult build() {
      return toBuild;
    }

    public ListOfRecordsByTableNameResultBuilder response(String value) {
      toBuild.response = value;
      return this;
    }
  }
}
